// General
import type {
    DifficultyNames,
    MapNames,
    RealMapNames,
    BossNames,
    BotNames,
    RealBotNames,
} from "../models/common";

export const zoneNames: Record<MapNames, string[]> = {
    bigmap: [
        "ZoneBrige",
        "ZoneCrossRoad",
        "ZoneDormitory",
        "ZoneGasStation",
        "ZoneFactoryCenter",
        "ZoneFactorySide",
        "ZoneOldAZS",
        "ZoneSnipeBrige",
        "ZoneSnipeTower",
        "ZoneSnipeFactory",
        "ZoneBlockPost",
        "ZoneBlockPostSniper",
        "ZoneBlockPostSniper3",
        "ZoneTankSquare",
        "ZoneWade",
        "ZoneCustoms",
        "ZoneScavBase",
    ],
    factory4_day: ["BotZone"],
    factory4_night: ["BotZone"],
    interchange: [
        "ZoneCenter",
        "ZoneCenterBot",
        "ZoneOLI",
        "ZoneIDEA",
        "ZoneRoad",
        "ZoneIDEAPark",
        "ZoneGoshan",
        "ZonePowerStation",
        "ZoneTrucks",
        "ZoneOLIPark",
    ],
    laboratory: [
        "BotZoneFloor1",
        "BotZoneFloor2",
        "BotZoneGate1",
        "BotZoneGate2",
        "BotZoneBasement",
    ],
    lighthouse: [
        "Zone_Containers",
        "Zone_Rocks",
        "Zone_Chalet",
        "Zone_Village",
        "Zone_Bridge",
        "Zone_OldHouse",
        "Zone_LongRoad",
        "Zone_DestroyedHouse",
        "Zone_SniperPeak",
        "Zone_Island",
        "Zone_TreatmentContainers",
        "Zone_TreatmentRocks",
        "Zone_RoofBeach",
        "Zone_TreatmentBeach",
        "Zone_Blockpost",
        "Zone_Hellicopter",
        "Zone_RoofContainers",
        "Zone_RoofRocks",
    ],
    rezervbase: [
        "ZoneRailStrorage",
        "ZonePTOR1",
        "ZonePTOR2",
        "ZoneBarrack",
        "ZoneBunkerStorage",
        "ZoneSubStorage",
        "ZoneSubCommand",
    ],
    sandbox: ["BotZone"],
    sandbox_high: ["BotZone"],
    shoreline: [
        "ZoneSanatorium1",
        "ZoneSanatorium2",
        "ZoneIsland",
        "ZoneGasStation",
        "ZoneMeteoStation",
        "ZonePowerStation",
        "ZoneBusStation",
        "ZoneRailWays",
        "ZonePort",
        "ZoneBunkeSniper",
        "ZonePowerStationSniper",
        "ZoneForestTruck",
        "ZoneForestSpawn",
        "ZoneSmuglers",
        "ZoneTunnel",
        "ZonePassClose",
        "ZoneBunker",
        "ZoneGreenHouses",
        "ZoneStartVillage",
        "ZoneForestGasStation",
    ],
    tarkovstreets: [
        "ZoneSW01",
        "ZoneConstruction",
        "ZoneCarShowroom",
        "ZoneCinema",
        "ZoneFactory",
        "ZoneHotel_1",
        "ZoneHotel_2",
        "ZoneConcordia_1",
        "ZoneConcordiaParking",
        "ZoneSnipeCinema",
        "ZoneSnipeCarShowroom",
        "ZoneSnipeBuilding",
        "ZoneSnipeSW01",
        "ZoneSW00",
        "ZoneCard1",
        "ZoneStilo",
        "ZoneColumn",
        "ZoneSnipeStilo",
        "ZoneMvd",
        "ZoneSnipeCard",
        "ZoneClimova",
    ],
    woods: [
        "ZoneClearVill",
        "ZoneHouse",
        "ZoneScavBase2",
        "ZoneWoodCutter",
        "ZoneBigRocks",
        "ZoneRoad",
        "ZoneHighRocks",
        "ZoneMiniHouse",
        "ZoneRedHouse",
        "ZoneDepo",
        "ZoneStoneBunker",
        "ZoneBrokenVill",
        "ZoneUsecBase",
    ],
};

export const difficultyNames: DifficultyNames[] = [
    "easy",
    "normal",
    "hard",
    "impossible",
];

export const mapNames: MapNames[] = [
    "bigmap",
    "factory4_day",
    "factory4_night",
    "interchange",
    "laboratory",
    "lighthouse",
    "rezervbase",
    "sandbox",
    "sandbox_high",
    "shoreline",
    "tarkovstreets",
    "woods",
];

export const bossNames: BossNames[] = [
    "bossBully",
    "bossGluhar",
    "bossKilla",
    "bossKojaniy",
    "bossSanitar",
    "bossTagilla",
    "bossKnight",
    "bossZryachiy",
    "bossBoar",
    "bossBoarSniper",
    "bossKolontay",
    "bossPartisan",
    "followerBigPipe",
    "followerBirdEye",
    "sectantPriest",
    "sectantOni",
    "sectantPredvestnik",
    "sectantPrizrak",
];

export const botNames: BotNames[] = [
    "pmcUSEC",
    "pmcBEAR",
    "pmcBot",
    "assault",
    "crazyAssaultEvent",
    "marksman",
    "exUsec",
    "arenaFighterEvent",
    "sectantWarrior",
];

export const realBotName: Record<RealBotNames, string> = {
    Usec: "pmcUSEC",
    Bear: "pmcBEAR",
    Sniper: "marksman",
    Scav: "assault",
    ScavEvent: "crazyAssaultEvent",
    ScavCursed: "cursedAssault",
    Rogue: "exUsec",
    Raider: "pmcBot",
    Smuggler: "arenaFighterEvent",
    Kaban: "bossBoar",
    KabanSniper: "bossBoarSniper",
    KabanAssault: "followerBoar",
    KabanClose1: "followerBoarClose1",
    KabanClose2: "followerBoarClose2",
    Reshala: "bossBully",
    ReshalaAssault: "followerBully",
    Glukhar: "bossGluhar",
    GlukharAssault: "followerGluharAssault",
    GlukharScout: "followerGluharScout",
    GlukharSecurity: "followerGluharSecurity",
    GlukharSniper: "followerGluharSnipe",
    Knight: "bossKnight",
    BigPipe: "followerBigPipe",
    BirdEye: "followerBirdEye",
    Shturman: "bossKojaniy",
    ShturmanAssault: "followerKojaniy",
    Kolontay: "bossKolontay",
    KolontayAssault: "followerKolontayAssault",
    KolontaySecurity: "followerKolontaySecurity",
    Partisan: "bossPartisan",
    Sanitar: "bossSanitar",
    SanitarAssault: "followerSanitar",
    Killa: "bossKilla",
    Tagilla: "bossTagilla",
    TagillaAssault: "followerTagilla",
    Zryachiy: "bossZryachiy",
    ZryachiyAssault: "followerZryachiy",
    CultistPriest: "sectantPriest",
    Cultist: "sectantWarrior",
    CultistOni: "sectantOni",
    CultistPredvestni: "sectantPredvestnik",
    CultistPrizrak: "sectantPrizrak",
};

export const realMapNames: Record<RealMapNames, string> = {
    Customs: "bigmap",
    Factory: "factory4_day",
    FactoryNight: "factory4_night",
    Interchange: "interchange",
    Laboratory: "laboratory",
    Lighthouse: "lighthouse",
    Reserve: "rezervbase",
    GroundZero: "sandbox",
    GroundZeroHigh: "sandbox_high",
    Shoreline: "shoreline",
    Streets: "tarkovstreets",
    Woods: "woods",
};
