export enum MapNames {
    Customs = "bigmap",
    Factory = "factory4_day",
    FactoryNight = "factory4_night",
    Interchange = "interchange",
    Laboratory = "laboratory",
    Lighthouse = "lighthouse",
    Reserve = "rezervbase",
    GroundZero = "sandbox",
    GroundZeroHigh = "sandbox_high",
    Shoreline = "shoreline",
    Streets = "tarkovstreets",
    Woods = "woods",
}

export const zoneNames: Record<MapNames, string[]> = {
    bigmap: [
        "ZoneBrige",
        "ZoneCrossRoad",
        "ZoneDormitory",
        "ZoneGasStation",
        "ZoneFactoryCenter",
        "ZoneFactorySide",
        "ZoneOldAZS",
        "ZoneSnipeBrige",
        "ZoneSnipeTower",
        "ZoneSnipeFactory",
        "ZoneBlockPost",
        "ZoneBlockPostSniper",
        "ZoneBlockPostSniper3",
        "ZoneTankSquare",
        "ZoneWade",
        "ZoneCustoms",
        "ZoneScavBase",
    ],
    factory4_day: ["BotZone"],
    factory4_night: ["BotZone"],
    interchange: [
        "ZoneCenter",
        "ZoneCenterBot",
        "ZoneOLI",
        "ZoneIDEA",
        "ZoneRoad",
        "ZoneIDEAPark",
        "ZoneGoshan",
        "ZonePowerStation",
        "ZoneTrucks",
        "ZoneOLIPark",
    ],
    laboratory: [
        "BotZoneFloor1",
        "BotZoneFloor2",
        "BotZoneGate1",
        "BotZoneGate2",
        "BotZoneBasement",
    ],
    lighthouse: [
        "Zone_Containers",
        "Zone_Rocks",
        "Zone_Chalet",
        "Zone_Village",
        "Zone_Bridge",
        "Zone_OldHouse",
        "Zone_LongRoad",
        "Zone_DestroyedHouse",
        "Zone_SniperPeak",
        "Zone_Island",
        "Zone_TreatmentContainers",
        "Zone_TreatmentRocks",
        "Zone_RoofBeach",
        "Zone_TreatmentBeach",
        "Zone_Blockpost",
        "Zone_Hellicopter",
        "Zone_RoofContainers",
        "Zone_RoofRocks",
    ],
    rezervbase: [
        "ZoneRailStrorage",
        "ZonePTOR1",
        "ZonePTOR2",
        "ZoneBarrack",
        "ZoneBunkerStorage",
        "ZoneSubStorage",
        "ZoneSubCommand",
    ],
    sandbox: ["BotZone"],
    sandbox_high: ["BotZone"],
    shoreline: [
        "ZoneSanatorium1",
        "ZoneSanatorium2",
        "ZoneIsland",
        "ZoneGasStation",
        "ZoneMeteoStation",
        "ZonePowerStation",
        "ZoneBusStation",
        "ZoneRailWays",
        "ZonePort",
        "ZoneBunkeSniper",
        "ZonePowerStationSniper",
        "ZoneForestTruck",
        "ZoneForestSpawn",
        "ZoneSmuglers",
        "ZoneTunnel",
        "ZonePassClose",
        "ZoneBunker",
        "ZoneGreenHouses",
        "ZoneStartVillage",
        "ZoneForestGasStation",
    ],
    tarkovstreets: [
        "ZoneSW01",
        "ZoneConstruction",
        "ZoneCarShowroom",
        "ZoneCinema",
        "ZoneFactory",
        "ZoneHotel_1",
        "ZoneHotel_2",
        "ZoneConcordia_1",
        "ZoneConcordiaParking",
        "ZoneSnipeCinema",
        "ZoneSnipeCarShowroom",
        "ZoneSnipeBuilding",
        "ZoneSnipeSW01",
        "ZoneSW00",
        "ZoneCard1",
        "ZoneStilo",
        "ZoneColumn",
        "ZoneSnipeStilo",
        "ZoneMvd",
        "ZoneSnipeCard",
        "ZoneClimova",
    ],
    woods: [
        "ZoneClearVill",
        "ZoneHouse",
        "ZoneScavBase2",
        "ZoneWoodCutter",
        "ZoneBigRocks",
        "ZoneRoad",
        "ZoneHighRocks",
        "ZoneMiniHouse",
        "ZoneRedHouse",
        "ZoneDepo",
        "ZoneStoneBunker",
        "ZoneBrokenVill",
        "ZoneUsecBase",
    ],
};

export const mapNames = [
    "bigmap",
    "factory4_day",
    "factory4_night",
    "interchange",
    "laboratory",
    "lighthouse",
    "rezervbase",
    "sandbox",
    "sandbox_high",
    "shoreline",
    "tarkovstreets",
    "woods",
];
